[project]
name = "localai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "chroma>=0.2.0",
    "langchain>=0.3.22",
    "langchain-chroma>=0.2.2",
    "langchain-ollama>=0.3.0",
    "pandas>=2.2.3",
]
